language: go

go_import_path: OntologyWithPOC

os:
  - linux
  - osx

go:
  - "1.12.x"

script:
  - env GO111MODULE=on make all-cross
  - env GO111MODULE=on go mod vendor
  - bash ./.travis.check-license.sh
  - bash ./.travis.gofmt.sh
  - bash ./.travis.gotest.sh
